begin;
create extension if not exists pgtap with schema extensions;
select plan(72);

select has_table('exam_delivery','protected_assignments','authoritative assignment table exists');
select has_column('exam_delivery','attempts','protected_assignment_id','attempts require assignment linkage');
select ok((select is_nullable='YES' from information_schema.columns where table_schema='exam_delivery' and table_name='attempts' and column_name='protected_assignment_id'),'generic open access permits an attempt without an assignment while assigned modes retain the FK');
select has_function('public','certsim_protected_create_assignment',array['uuid','uuid','text','text','timestamptz','timestamptz','integer','text','text'],'fixed assignment wrapper exists');
select has_function('exam_delivery','create_protected_assignment',array['uuid','uuid','text','text','timestamptz','timestamptz','integer','text','text'],'private assignment operation exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='exam_delivery' and c.relname='protected_assignments'),'RLS enabled');
select ok(not has_table_privilege('anon','exam_delivery.protected_assignments','SELECT,INSERT,UPDATE,DELETE'),'anon has no table access');
select ok(not has_table_privilege('authenticated','exam_delivery.protected_assignments','SELECT,INSERT,UPDATE,DELETE'),'authenticated has no table access');
select ok(not has_table_privilege('service_role','exam_delivery.protected_assignments','SELECT,INSERT,UPDATE,DELETE'),'service role has no table access');
select ok(not has_function_privilege('public','public.certsim_protected_create_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'PUBLIC denied wrapper');
select ok(not has_function_privilege('anon','public.certsim_protected_create_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'anon denied wrapper');
select ok(has_function_privilege('authenticated','public.certsim_protected_create_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'authenticated can use fixed wrapper');
select ok(not has_function_privilege('service_role','public.certsim_protected_create_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'service role denied wrapper');
select ok(not has_function_privilege('service_role','exam_delivery.create_protected_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'service role denied private operation');
select ok((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='create_protected_assignment'),'private operation is SECURITY DEFINER');
select ok(not (select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='certsim_protected_create_assignment'),'fixed wrapper is SECURITY INVOKER');
select ok(has_schema_privilege('authenticated','exam_delivery','USAGE'),'authenticated has minimum private schema usage');
select ok(has_function_privilege('authenticated','exam_delivery.create_protected_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'authenticated can execute the checked private assignment operation');
select ok(not has_function_privilege('public','exam_delivery.create_protected_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'PUBLIC denied private assignment operation');
select ok(not has_function_privilege('anon','exam_delivery.create_protected_assignment(uuid,uuid,text,text,timestamptz,timestamptz,integer,text,text)','EXECUTE'),'anon denied private assignment operation');
select ok(not has_schema_privilege('public','exam_delivery','USAGE'),'PUBLIC denied private schema usage');
select ok(not has_schema_privilege('anon','exam_delivery','USAGE'),'anon denied private schema usage');
select ok((select proconfig @> array['search_path=""','statement_timeout=10s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='create_protected_assignment' and p.pronargs=9),'private operation has empty path and timeout');
select is((select count(*)::integer from pg_policies where schemaname='exam_delivery' and tablename='protected_assignments'),0,'no direct RLS policy opens assignment rows');
select is((select count(*)::integer from information_schema.role_table_grants where table_schema='exam_delivery' and table_name='protected_assignments' and grantee in ('PUBLIC','anon','authenticated','service_role')),0,'no direct grants leak assignment rows');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_package_profile_fk'),1,'composite package/profile FK exists');
select is((select count(*)::integer from pg_indexes where schemaname='exam_delivery' and tablename='protected_assignments' and indexname='protected_assignments_one_active_identity_idx'),1,'active assignment uniqueness index exists');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_maximum_attempts_check'),1,'positive attempt constraint exists');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_review_policy_check'),1,'review policy constraint exists');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_answer_policy_check'),1,'answer policy constraint exists');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_window_check'),1,'time window constraint exists');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.protected_assignments'::regclass and conname='protected_assignments_lifecycle_check'),1,'lifecycle state constraint exists');
select ok((select pg_get_functiondef(p.oid) !~* 'user_metadata' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='create_protected_assignment'),'authorization ignores user metadata');
select ok((select pg_get_functiondef(p.oid) ~ 'auth.uid\(\)' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='create_protected_assignment'),'actor comes from auth.uid');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='certsim_protected_create_assignment' and p.prosecdef),'advisor rule 0029 cannot apply to the public wrapper');
select ok((select pg_get_functiondef(p.oid) !~* 'public.exam_assignments' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='check_eligibility_ai901_v1'),'legacy assignments cannot grant AI-901 eligibility');
select ok((select pg_get_functiondef(p.oid) ~* 'for update of a' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_attempt_ai901_v1'),'AI-901 start serializes assignment allowance');
select ok((select pg_get_functiondef(p.oid) ~* 'review_release_policy.*never' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='get_review'),'review enforces assignment release policy');

select has_table('exam_delivery','attempt_technical_recoveries','technical recovery audit table exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='exam_delivery' and c.relname='attempt_technical_recoveries'),'recovery audit RLS enabled');
select ok(not has_table_privilege('anon','exam_delivery.attempt_technical_recoveries','SELECT,INSERT,UPDATE,DELETE'),'anon denied recovery audit');
select ok(not has_table_privilege('authenticated','exam_delivery.attempt_technical_recoveries','SELECT,INSERT,UPDATE,DELETE'),'authenticated denied recovery audit');
select ok(not has_table_privilege('service_role','exam_delivery.attempt_technical_recoveries','SELECT,INSERT,UPDATE,DELETE'),'service role denied recovery audit');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.attempt_technical_recoveries'::regclass and conname='attempt_technical_recoveries_assignment_unique'),1,'one recovery per assignment');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.attempt_technical_recoveries'::regclass and conname='attempt_technical_recoveries_interrupted_attempt_id_key'),1,'interrupted attempt unique');
select has_function('public','certsim_protected_resume_current_attempt',array['uuid','text','text'],'current-attempt wrapper exists');
select has_function('exam_delivery','resume_current_attempt',array['uuid','text','text'],'private current-attempt operation exists');
select ok(not (select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='certsim_protected_resume_current_attempt'),'current wrapper is invoker');
select ok((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='resume_current_attempt'),'current operation is definer');
select ok(has_function_privilege('service_role','public.certsim_protected_resume_current_attempt(uuid,text,text)','EXECUTE'),'service role can call fixed current wrapper');
select ok(not has_function_privilege('authenticated','public.certsim_protected_resume_current_attempt(uuid,text,text)','EXECUTE'),'authenticated cannot bypass Edge current route');
select ok(not has_function_privilege('anon','public.certsim_protected_resume_current_attempt(uuid,text,text)','EXECUTE'),'anon denied current wrapper');
select has_function('public','certsim_protected_authorize_technical_recovery',array['uuid','text'],'recovery wrapper exists');
select has_function('exam_delivery','authorize_technical_recovery',array['uuid','text'],'private recovery operation exists');
select ok(not (select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='certsim_protected_authorize_technical_recovery'),'recovery wrapper is invoker');
select ok((select prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_technical_recovery'),'recovery operation is definer');
select ok(has_function_privilege('authenticated','public.certsim_protected_authorize_technical_recovery(uuid,text)','EXECUTE'),'authenticated owner boundary enabled');
select ok(not has_function_privilege('service_role','public.certsim_protected_authorize_technical_recovery(uuid,text)','EXECUTE'),'service role denied recovery wrapper');
select ok((select pg_get_functiondef(p.oid) ~ 'auth.uid\(\)' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_technical_recovery'),'recovery actor derives from auth.uid');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.attempt_technical_recoveries'::regclass and conname='attempt_technical_recoveries_reason_check'),1,'recovery reason is fixed');
select ok((select pg_get_functiondef(p.oid) !~* 'delete|truncate' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_technical_recovery'),'recovery preserves audit data');
select ok((select pg_get_functiondef(p.oid) ~* 'attempt_technical_recoveries.*interrupted_attempt_id' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='check_eligibility_ai901_v1'),'AI-901 eligibility excludes only audited interruption');
select ok((select pg_get_functiondef(p.oid) ~* 'replacement_attempt_id.*replacement_started_at' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_attempt_ai901_v1'),'AI-901 replacement relationship is recorded');
select ok((select proconfig @> array['search_path=""','statement_timeout=10s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_technical_recovery'),'recovery has empty path and timeout');
select is((select count(*)::integer from pg_policies where schemaname='exam_delivery' and tablename='attempt_technical_recoveries'),0,'no recovery audit RLS policies');
select has_function('exam_delivery','submit_attempt_idempotent',array['uuid','uuid','uuid'],'idempotent submit adapter exists');
select ok((select proconfig @> array['search_path=""','statement_timeout=15s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='submit_attempt_idempotent'),'submit adapter has empty path and timeout');
select ok((select pg_get_functiondef(p.oid) ~* 'submission_id=p_submission_id' and pg_get_functiondef(p.oid) ~* 'get_result' and pg_get_functiondef(p.oid) ~* 'submit_attempt' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='submit_attempt_idempotent'),'identical replay precedes authoritative scorer delegation');
select has_function('exam_delivery','authorize_unique_ai901_technical_recovery',array['text'],'identity-derived recovery resolver exists');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=10s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_unique_ai901_technical_recovery'),'identity recovery is bounded private authority');
select ok((select not prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='certsim_protected_authorize_unique_ai901_recovery'),'identity recovery public wrapper is invoker');
select ok((select pg_get_functiondef(p.oid) ~* 'owner_membership\.user_id=v_actor' and pg_get_functiondef(p.oid) ~* 'owner_membership\.organisation_id=pa\.organisation_id' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_unique_ai901_technical_recovery'),'identity recovery candidate is scoped to the invoking owner organisation');

select * from finish();
rollback;
