begin;
select plan(20);
select has_column('exam_delivery','attempts','source_assignment_id','attempts preserve public assignment identity');
select has_column('exam_delivery','attempts','source_organisation_id','attempts preserve organisation scope');
select has_column('exam_delivery','attempts','source_campus_id','attempts preserve campus scope');
select has_column('exam_delivery','attempts','source_group_id','attempts preserve group scope');
select has_column('exam_delivery','attempts','attribution_source','attempts classify attribution source');
select has_function('exam_delivery','start_assignment_attempt',array['uuid','text','text','uuid','uuid'],'exact assignment start exists');
select has_function('exam_delivery','staff_dashboard_scope',array['uuid','jsonb'],'bounded staff hierarchy exists');
select has_function('public','certsim_protected_staff_dashboard_scope',array['uuid','jsonb'],'fixed Edge wrapper exists');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=12s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='staff_dashboard_scope'),'staff hierarchy is bounded definer code');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=15s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_assignment_attempt'),'assignment start is bounded definer code');
select ok(not has_function_privilege('authenticated','public.certsim_protected_staff_dashboard_scope(uuid,jsonb)','EXECUTE') and has_function_privilege('service_role','public.certsim_protected_staff_dashboard_scope(uuid,jsonb)','EXECUTE'),'staff hierarchy remains behind Edge service boundary');
select ok(not has_function_privilege('authenticated','public.certsim_protected_start_attempt(uuid,text,text,uuid,uuid)','EXECUTE') and has_function_privilege('service_role','public.certsim_protected_start_attempt(uuid,text,text,uuid,uuid)','EXECUTE'),'assignment start remains behind Edge service boundary');
select ok((select pg_get_functiondef(p.oid) ~ 'analytics_eligible is true' and pg_get_functiondef(p.oid) ~ 'assigned_assessment' and pg_get_functiondef(p.oid) ~ 'self_directed_exam' and pg_get_functiondef(p.oid) ~ 'legacy_authoritative' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='staff_dashboard_scope'),'scoped history includes only classified authoritative assessment purposes');
select ok((select pg_get_functiondef(p.oid) ~ 'v_assignment.profile_id<>p_profile_key' and pg_get_functiondef(p.oid) ~ 'm.group_id=v_assignment.group_id' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_assignment_attempt'),'assignment start validates exact profile and learner scope');
select ok((select count(*)=2 from pg_trigger where not tgisinternal and tgname in ('classify_attempt_attribution_before_insert','guard_attempt_attribution_mutation')),'attribution classification and immutability triggers exist');
select has_function('exam_delivery','list_current_attempt_bindings',array['uuid','text','text'],'read-only current binding reconciliation exists');
select has_function('public','certsim_protected_list_current_attempt_bindings',array['uuid','text','text'],'fixed current binding Edge wrapper exists');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=5s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='list_current_attempt_bindings'),'binding reconciliation is bounded definer code');
select ok(not has_function_privilege('authenticated','public.certsim_protected_list_current_attempt_bindings(uuid,text,text)','EXECUTE') and has_function_privilege('service_role','public.certsim_protected_list_current_attempt_bindings(uuid,text,text)','EXECUTE'),'binding reconciliation remains behind Edge service boundary');
select ok((select pg_get_functiondef(p.oid) !~* '(insert|update|delete)[[:space:]]+exam_delivery\\.attempts' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='list_current_attempt_bindings'),'binding reconciliation cannot mutate attempts');
select * from finish();
rollback;
