begin;
select plan(68);
select has_column('exam_delivery','attempts','purpose','attempt purpose exists');
select has_column('exam_delivery','attempts','practice_configuration','practice configuration exists');
select has_column('exam_delivery','attempts','language_preference','language preference exists');
select col_not_null('exam_delivery','attempts','purpose','attempt purpose is required');
select has_table('exam_delivery','practice_policies','practice policies exist');
select has_table('exam_delivery','practice_feedback_releases','feedback release audit exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='exam_delivery' and c.relname='practice_policies'),'practice policies use RLS');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='exam_delivery' and c.relname='practice_feedback_releases'),'feedback releases use RLS');
select has_function('exam_delivery','practice_availability',array['uuid','jsonb']);
select has_function('exam_delivery','prune_practice_selection',array['uuid','uuid','jsonb','integer']);
select has_function('exam_delivery','start_practice',array['uuid','jsonb']);
select has_function('exam_delivery','materialize_attempt_items',array['uuid','uuid','integer']);
select has_function('exam_delivery','check_practice_item',array['uuid','uuid','uuid','integer','uuid']);
select has_function('exam_delivery','list_history',array['uuid','text','text','integer']);
select has_function('exam_delivery','history_summary',array['uuid','text']);
select has_function('exam_delivery','print_summary',array['uuid','uuid']);
select ok((select bool_and(prosecdef and proconfig @> array['search_path=""']) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname in ('practice_availability','prune_practice_selection','start_practice','check_practice_item','list_history','history_summary','print_summary')),'private operations are definer functions with empty search paths');
select ok(not has_function_privilege('authenticated','public.certsim_protected_start_practice(uuid,jsonb)','EXECUTE'),'browser cannot call practice start directly');
select ok(has_function_privilege('service_role','public.certsim_protected_start_practice(uuid,jsonb)','EXECUTE'),'fixed Edge runtime may call practice start');
select ok(not has_function_privilege('authenticated','public.certsim_protected_list_history(uuid,text,text,integer)','EXECUTE'),'browser cannot call protected history directly');
select ok(has_function_privilege('service_role','public.certsim_protected_list_history(uuid,text,text,integer)','EXECUTE'),'fixed Edge runtime may call protected history');
select is((select count(*)::integer from exam_delivery.practice_policies),0,'migration enables no practice policy');
select is((select count(*)::integer from exam_delivery.practice_feedback_releases),0,'migration creates no feedback release');
select is((select count(*)::integer from exam_delivery.attempts),0,'migration creates no attempt');
select ok((select pg_get_functiondef(p.oid) ~ 'analytics_eligible is true' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='history_summary'),'latest and best statistics use immutable student assessment eligibility only');
select ok((select pg_get_functiondef(p.oid) ~ 'exam_delivery.can_use_profile' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_attempt_continuation'),'practice continuation uses the unified profile-access contract');
select ok((select pg_get_functiondef(p.oid) !~ 'exam_delivery.exam_access_learners' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='authorize_attempt_continuation'),'practice continuation no longer depends on the legacy controlled-beta allowlist');
select ok(not coalesce((select bool_or(x.grantee=0 and x.privilege_type='EXECUTE') from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x where n.nspname='exam_delivery' and p.proname='materialize_attempt_items'),false),'shared materializer denies PUBLIC');
select ok(not has_function_privilege('anon','exam_delivery.materialize_attempt_items(uuid,uuid,integer)','EXECUTE'),'shared materializer denies anon');
select ok(not has_function_privilege('authenticated','exam_delivery.materialize_attempt_items(uuid,uuid,integer)','EXECUTE'),'shared materializer denies authenticated');
select ok(not has_function_privilege('service_role','exam_delivery.materialize_attempt_items(uuid,uuid,integer)','EXECUTE'),'shared materializer denies service role');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=15s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='materialize_attempt_items'),'shared materializer is bounded and search-path safe');
select ok((select pg_get_functiondef(p.oid) !~ 'check_eligibility_v2' and pg_get_functiondef(p.oid) !~ 'from exam_delivery.protected_assignments' and pg_get_functiondef(p.oid) ~ 'practice_availability' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_practice'),'practice start uses practice authorization and no assignment lookup');
select ok((select pg_get_functiondef(p.oid) ~ 'check_eligibility_v2' and pg_get_functiondef(p.oid) ~ 'assigned_assessment' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_attempt_v2'),'assessment start preserves assessment authorization and purpose');
select ok((select pg_get_functiondef(p.oid) ~ 'materialize_attempt_items' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_practice_issue59_attribution_base'),'practice start implementation reaches only the private shared materializer after authorization');
select ok((select pg_get_functiondef(p.oid) ~ 'materialize_attempt_items' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_attempt_v2'),'assessment start reaches the same private shared materializer after authorization');
select has_function('exam_delivery','discover_current_attempt',array['uuid','text','text','text','text','text'],'private purpose-aware current discovery exists');
select has_function('public','certsim_protected_discover_current_attempt',array['uuid','text','text','text','text','text'],'fixed Edge current-discovery wrapper exists');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=5s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='discover_current_attempt'),'current discovery is bounded definer code with empty search path');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=5s'] from pg_proc p where p.oid=to_regprocedure('public.certsim_protected_discover_current_attempt(uuid,text,text,text,text,text)')),'fixed wrapper is bounded definer code because the private helper denies every externally usable role');
select ok(not has_function_privilege('public','exam_delivery.discover_current_attempt(uuid,text,text,text,text,text)','EXECUTE'),'PUBLIC denied private current discovery');
select ok(not has_function_privilege('anon','exam_delivery.discover_current_attempt(uuid,text,text,text,text,text)','EXECUTE'),'anon denied private current discovery');
select ok(not has_function_privilege('authenticated','exam_delivery.discover_current_attempt(uuid,text,text,text,text,text)','EXECUTE'),'authenticated denied private current discovery');
select ok(not has_function_privilege('service_role','exam_delivery.discover_current_attempt(uuid,text,text,text,text,text)','EXECUTE'),'service role denied private current discovery');
select ok(has_function_privilege('service_role','public.certsim_protected_discover_current_attempt(uuid,text,text,text,text,text)','EXECUTE'),'Edge service role may call only the fixed wrapper');
select ok((select pg_get_functiondef(p.oid) !~ 'check_(assessment_)?eligibility' and pg_get_functiondef(p.oid) ~ 'authorize_attempt_continuation' and pg_get_functiondef(p.oid) ~ 'a.owner_id=p_actor_id' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='discover_current_attempt'),'current discovery is owner-first and purpose-authorized without pre-discovery assessment eligibility');
select ok((select pg_get_functiondef(p.oid) ~ 'resume_current_attempt_ai901_v1' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='discover_current_attempt'),'legacy AI-901 current discovery remains delegated to its existing path');
select has_table('exam_delivery','practice_attempt_expirations','practice expiration audit exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='exam_delivery' and c.relname='practice_attempt_expirations'),'practice expiration audit uses RLS');
select ok(not has_table_privilege('anon','exam_delivery.practice_attempt_expirations','SELECT,INSERT,UPDATE,DELETE'),'anon denied practice expiration audit');
select ok(not has_table_privilege('authenticated','exam_delivery.practice_attempt_expirations','SELECT,INSERT,UPDATE,DELETE'),'authenticated denied practice expiration audit');
select ok(not has_table_privilege('service_role','exam_delivery.practice_attempt_expirations','SELECT,INSERT,UPDATE,DELETE'),'service role denied practice expiration audit');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.practice_attempt_expirations'::regclass and conname='practice_attempt_expirations_expired_attempt_id_key'),1,'an expired practice attempt is transitioned once');
select is((select count(*)::integer from pg_constraint where conrelid='exam_delivery.practice_attempt_expirations'::regclass and conname='practice_attempt_expirations_replacement_attempt_id_key'),1,'one audit row binds one replacement');
select ok((select pg_get_functiondef(p.oid) ~ 'pg_advisory_xact_lock' and pg_get_functiondef(p.oid) ~ 'practice_window_expired' and pg_get_functiondef(p.oid) ~ 'status=''expired''' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_practice_issue59_attribution_base'),'practice start atomically locks, expires, audits, and replaces stale practice');
select ok((select pg_get_functiondef(p.oid) ~ 'protected_assignment_id is not null' and pg_get_functiondef(p.oid) !~ 'status=''expired''[\s\S]+assigned_assessment' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='start_practice_issue59_attribution_base'),'practice expiry path excludes assigned assessments');
select is((select count(*)::integer from exam_delivery.practice_attempt_expirations),0,'migration creates no expiration audit row');
select ok((select pg_get_functiondef(p.oid) ~ '''serverAuthoritative'', ar.server_authoritative' and pg_get_functiondef(p.oid) ~ 'ar.server_authoritative = true' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='get_result'),'protected result authority is generated from the constrained result row');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=15s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='get_result'),'protected result lookup is bounded definer code with empty search path');
select ok(not has_function_privilege('authenticated','exam_delivery.get_result(uuid,uuid)','EXECUTE') and has_function_privilege('service_role','exam_delivery.get_result(uuid,uuid)','EXECUTE'),'protected result lookup retains the fixed Edge service-role boundary');
select has_function('exam_delivery','staff_analytics',array['uuid'],'complete scoped staff analytics exists');
select has_function('public','certsim_protected_staff_analytics',array['uuid'],'fixed Edge staff analytics wrapper exists');
select ok((select prosecdef and proconfig @> array['search_path=""','statement_timeout=12s'] from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='staff_analytics'),'staff analytics is bounded definer code with an empty search path');
select ok(not has_function_privilege('authenticated','public.certsim_protected_staff_analytics(uuid)','EXECUTE') and has_function_privilege('service_role','public.certsim_protected_staff_analytics(uuid)','EXECUTE'),'staff analytics remains behind the fixed Edge service-role boundary');
select ok(has_function_privilege('authenticated','public.certsim_grant_purchase_entitlement(uuid,uuid,uuid[],text,text,timestamptz)','EXECUTE') and not has_function_privilege('service_role','public.certsim_grant_purchase_entitlement(uuid,uuid,uuid[],text,text,timestamptz)','EXECUTE'),'purchase entitlement grant requires an authenticated internally authorized operator');
select has_index('exam_delivery','exam_entitlements','exam_entitlements_revoked_by_idx','entitlement revocation actor foreign key is indexed');
select ok((select pg_get_functiondef(p.oid) ~ 'legacy_authoritative' and pg_get_functiondef(p.oid) ~ 'staff_can_view_learner' and pg_get_functiondef(p.oid) ~ 'a.user_id is not null' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='print_summary'),'print summary supports scoped content-free legacy detail while excluding detached rows');
select ok((select pg_get_functiondef(p.oid) ~ 'analytics_eligible is true' and pg_get_functiondef(p.oid) ~ 'legacy_authoritative' and pg_get_functiondef(p.oid) ~ 'staff_can_view_learner' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='exam_delivery' and p.proname='staff_analytics'),'staff aggregates are scope-complete and purpose-aware with legacy history retained');
select * from finish();
rollback;
